# Generated by Django 5.1.1 on 2024-09-27 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fotografiia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
