# Generated by Django 5.1.1 on 2024-09-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_fotografiia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_fotografiia',
            new_name='data_fotografia',
        ),
    ]
